apiVersion: apps/v1
kind: Deployment
metadata:
  name: cernica-department-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cernica-department-webapi-label
  template:
    metadata:
      labels:
        pod: cernica-department-webapi-label
    spec:
      volumes:
        - name: init-scripts
          configMap:
            name: cernica-department-webapi-mongodb-init
      initContainers:
        - name: init-mongodb
          image: mongo:latest
          imagePullPolicy: Always
          command: ['mongosh', "--nodb", '-f', '/scripts/init-db.js']
          volumeMounts:
          - name: init-scripts
            mountPath: /scripts
          env:
             - name: DEPARTMENT_API_PORT
               value: "8080"
             - name: DEPARTMENT_API_MONGODB_HOST
               value: mongodb
             - name: DEPARTMENT_API_MONGODB_PORT
               value: "27017"
             - name: DEPARTMENT_API_MONGODB_USERNAME
               value: "root"
             - name: DEPARTMENT_API_MONGODB_PASSWORD
               value: "neUhaDnes"
             - name: DEPARTMENT_API_MONGODB_DATABASE
               valueFrom:
                 configMapKeyRef:
                   name: cernica-department-webapi-config
                   key: database
             - name: DEPARTMENT_API_MONGODB_COLLECTION
               valueFrom:
                 configMapKeyRef:
                   name: cernica-department-webapi-config
                   key: collection
             - name: RETRY_CONNECTION_SECONDS
               value: "5"
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.01"
            limits:
              memory: "256Mi"
              cpu: "0.1"
      containers:
        - name: cernica-department-webapi-container
          image: thomascodesthings/department-webapi:latest
          imagePullPolicy: Always
          ports:
            - name: webapi-port
              containerPort: 8080
          env:
            - name: DEPARTMENT_API_ENVIRONMENT
              value: production
            - name: DEPARTMENT_API_PORT
              value: "8080"
            - name: DEPARTMENT_API_MONGODB_HOST
              value: mongodb
            - name: DEPARTMENT_API_MONGODB_PORT
              value: "27017"
              # change to actual value
            - name: DEPARTMENT_API_MONGODB_USERNAME
              value: "root"
              # change to actual value
            - name: DEPARTMENT_API_MONGODB_PASSWORD
              value: "neUhaDnes"
            - name: DEPARTMENT_API_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cernica-department-webapi-config
                  key: database
            - name: DEPARTMENT_API_MONGODB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: cernica-department-webapi-config
                  key: collection
            - name: DEPARTMENT_API_MONGODB_TIMEOUT_SECONDS
              value: "5"
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.01"
            limits:
              memory: "512Mi"
              cpu: "0.3"
