apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: cernica-department-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: cernica-department-webapi-config
    literals:
      - database=cernica-department
      - collection=department
patches:
 - path: patches/webapi.deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: cernica-department-webapi