kind: Service
apiVersion: v1
metadata:
  name: cernica-department-webapi
spec:
  selector:
    pod: cernica-department-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port